var contacts,groups;groups=contacts="";function setmessage(a,d){var c;document.getElementById("txt_msg").value=document.getElementById(a).innerHTML.toString().replace("&amp;","&");c=document.getElementById("txt_msg").value.length;document.getElementById("txt_count").value=c;window.document.getElementById("hf_msg").value=d+"-"+a;alertMsgLength()}
function loadcontacts(){var a=document.getElementById("txt_mobileno");a!=null&&a.focus();a="getcontactlist.aspx?id="+Math.random();var d="t="+Math.random();a=new Ajax.Request(a,{method:"get",postBody:d,onSuccess:function(c){var b=c.responseText;c=b.split(":");b=b.replace(":",",");b=new AutoSuggestControl(document.getElementById("txt_mobileno"),new StateSuggestions(b));groups=c[1];contacts=c[0]},onFailure:function(c){return false}});a=(new Date).getHours();loadtemplates(1);document.getElementById("s0")&&
initsnow();disableyesno(false)}var strMsg,finalvalue;finalvalue="";
function checkmsgform(){var a=document.getElementById("txt_mobileno").value,d=trimAll(document.getElementById("txt_msg").value);if(a==""){window.alert("Please enter the Mobile Number !!");document.getElementById("txt_mobileno").focus();return false}if(!formatnumber()){finalvalue="";document.getElementById("txt_mobileno").focus();return false}if(d==""){window.alert("Please enter your SMS message !!");document.getElementById("txt_msg").focus();return false}a=document.getElementById("txt_msg").value.indexOf("<");
d=document.getElementById("txt_msg").value.indexOf(">");if(a>0){document.getElementById("txt_msg").value=document.getElementById("txt_msg").value.replace(/</g," ");document.getElementById("txt_msg").value=document.getElementById("txt_msg").value.replace(/>/g," ")}a=trimAll(document.getElementById("txt_msg").value).length;document.getElementById("txt_count").value=a;disableyesno(true);document.getElementById("act_mnos").value=finalvalue}
function disableyesno(a){if(a){document.getElementById("txtHint").innerHTML="Sending SMS Please Wait.....";document.getElementById("txtHint").style.display="block";document.getElementById("btnclear").disabled=true;document.getElementById("btnsendsms").disabled=true;document.getElementById("txt_mobileno").style.color="gray";document.getElementById("txt_msg").style.color="gray"}else{document.getElementById("txtHint").innerHTML="";document.getElementById("txtHint").style.display="none";document.getElementById("btnclear").disabled=
false;document.getElementById("btnsendsms").disabled=false;document.getElementById("txt_mobileno").style.color=null;document.getElementById("txt_msg").style.color=null}}var charCount=0;
function alertMsgLength(){var a;if(charCount==0)if(document.getElementById("isAdFree")){charCount=document.getElementById("isAdFree").value;if(charCount==""||isNaN(charCount)||charCount!=148)charCount=140}else charCount=148;document.getElementById("txtHint").style.display="none";if(document.getElementById("txt_msg").value.replace(/\r\n/g,"\n").length>charCount){a=trimAll(document.getElementById("txt_msg").value.replace(/\r\n/g,"\n"));document.getElementById("txt_msg").value=a.substring(0,charCount);document.getElementById("txt_msg").focus();
return false}a="";a=trimAll(document.getElementById("txt_msg").value.replace(/\r\n/g,"\n"));a=a.length;document.getElementById("txt_count").value=charCount-a+" characters left "}function ClearTextFields(){document.getElementById("txtHint").style.display="none";document.getElementById("frmcompose").reset();document.getElementById("txt_mobileno").value="";document.getElementById("txt_msg").value="";document.getElementById("txt_mobileno").focus();document.getElementById("hf_msg").value="";return false}
var fulllength_mnos="",fulllength_mnos_post="",other_country_mobile=0,max_mobiles=0;
function formatnumber(){var a=trimAll(document.getElementById("txt_msg").value);finalvalue=fulllength_mnos_post=fulllength_mnos="";var d=other_country_mobile=0;d=document.getElementById("isAdFree").value;var c=[],b,e,g,f;c=trimAll(document.getElementById("txt_mobileno").value).split(",");e=f=false;if(c.length>100){alert("Cannot send More than 100 SMS at a time");return false}max_mobiles=c.length-1;for(x=0;x<c.length;x++){b=trimAll(c[x].toString());b=b.toLowerCase();if(x==0)fulllength_mnos="";if(groups==
null||(","+groups+",").toLowerCase().search(","+b+",")==-1){if(f){alert("Send SMS to either contacts or group.");return false}if(contacts.indexOf(b)!=-1){e=b.indexOf("<");g=b.indexOf(">");if(e>0)b=b.substring(e+1,g)}if(!validatemobilenumber(b))return false;e=true;if(b.length==10&&(b.indexOf("9")==0||b.indexOf("8")==0)&&a.length>80){fulllength_mnos=fulllength_mnos+","+b;fulllength_mnos_post=fulllength_mnos_post+"91"+b+","}else other_country_mobile+=1;if(b.length==10&&(b.indexOf("9")==0||b.indexOf("8")==
0))b="91"+b}else{if(f){alert("Send SMS to one group Only");return false}if(e){alert("Send SMS to either contacts or group.");return false}f=true}finalvalue+=b+","}if(!f)if(a.length>80&&(d==""||isNaN(d)||d!=148))if(fulllength_mnos!=""&&other_country_mobile!=0)if(confirm("More than 80 character message will be sent to only for INDIAN Mobiles: \n"+fulllength_mnos.substring(1))){finalvalue=fulllength_mnos_post;return true}else return false;else if(fulllength_mnos==""&&other_country_mobile!=0){alert("You cannot sent more than 80 character message to any of the mobiles out side INDIA -> Team Q-read techno , Calicut, Kerala, INDIA");
return false}document.getElementById("txt_msg").value=trimAll(document.getElementById("txt_msg").value);return true}
function displayText(){var a="no="+document.getElementById("hf").value,d;a=new Ajax.Request("getText.aspx",{method:"get",postBody:a,onSuccess:function(c){d=c.responseText.split("|");document.getElementById("hf").value=d[0];document.getElementById("p2").innerHTML=d[1]+'<a href="faqs.aspx">read more...</a>';document.getElementById("p2").style.visibility="visible"},onFailure:function(c){document.getElementById("p2").innerHTML="Cannot connect to www.qreadtechno.com. Please try later!";return false}});return false}
;